### ISSUE TITLE
[S1 - PBI1] Landing Page ( Register dan Log In Akun )

### ISSUE THREAD

**Issue by sascasuhita** [SI-RPL-2022/SI4303_G_TRACSESS#1]
Saya sebagai admin ingin login pada akun sehingga dapat memantau pekerjaan pada website
Saya sebagai petugas ingin login pada akun sehingga dapat mengirimkan update terbaru pemberhentian tasiun pada website
Saya sebagai customer ingin register dan login pada akun agar dapat memesan tiket melalui website

1. Deskripsi Use Case Diagram : 
Register
<img width="416" alt="Register1" src="https://user-images.githubusercontent.com/92259942/160513543-8088f573-2c0b-4bbb-b492-d4f4536f865c.png">
Login
<img width="407" alt="Login1" src="https://user-images.githubusercontent.com/92259942/160513594-e431c948-0ec8-4236-aaa9-f117c7f323b3.png">

2. Activity Diagram : 
Register oleh Customer
![Register](https://user-images.githubusercontent.com/92259942/160241675-fe1db0da-378c-4385-a25b-024f53159297.png)

Login oleh User (Admin, Petugas, dan Customer)
![Log In](https://user-images.githubusercontent.com/92259942/160241641-30e767e3-c9c7-4773-ab39-bb1cb674dd41.png)

3. Mock Up

Register :
<img width="326" alt="REGISTER" src="https://user-images.githubusercontent.com/92259942/160244075-561dc405-24a2-4d29-bbaa-82d733b0f2f6.png">
Login :
<img width="323" alt="LOGIN" src="https://user-images.githubusercontent.com/92259942/160244086-581f619e-58e7-4ac1-849b-4f08a67733a7.png">

**Comment by ekkynovrizalam** [comment]
ini harus jadi satu sama issue2 lain yang semacam login seperti  #8 #4 dan juga dijadikan satu dengan PBI register #5 @sascasuhita @TaufikRafli138 @emasdai @reynaldyaditya

**Comment by sascasuhita** [comment]
> ini harus jadi satu sama issue2 lain yang semacam login seperti #8 #4 dan juga dijadikan satu dengan PBI register #5 @sascasuhita @TaufikRafli138 @emasdai @reynaldyaditya

Baik pak, sudah saya jadikan satu
