### ISSUE TITLE
[S2-PBI11] Pencetakan e-ticket

### ISSUE THREAD

**Issue by aqilahaunia** [SI-RPL-2022/SI4303_G_TRACSESS#10]
Customer dapat mencetak e-ticket setelah proses pemesanan tiket

Usecase Diagram : 

![pbi11](https://user-images.githubusercontent.com/92071753/165198544-6628c1fe-f596-436e-8b8f-8366c27a3fcb.jpg)

Activity Diagram :

![e-ticket (1)](https://user-images.githubusercontent.com/92071753/170886360-dc1176b5-71aa-4f6f-a08d-aeda750a78b2.png)

Mockup :

![E-Ticket](https://user-images.githubusercontent.com/92071753/170878882-090b8b81-c1a3-4465-a57b-d2f32a718498.png)

Video Penjelasan :

https://user-images.githubusercontent.com/92071753/170883974-764f8e31-f5b8-4738-9974-5fab9bda3087.mp4

**Comment by ekkynovrizalam** [comment]
ada codeqr
