### ISSUE TITLE
[S2 - PBI14] Boarding Pelanggan

### ISSUE THREAD

**Issue by sascasuhita** [SI-RPL-2022/SI4303_G_TRACSESS#12]
Saya sebagai petugas ingin melakukan boarding pelanggan

1. Deskripsi Use Case
<img width="404" alt="boarding penumpang" src="https://user-images.githubusercontent.com/92259942/165211742-a87e311c-d4ba-4ca6-9031-b19e3d947861.png">

2. Activity Diagram
![boarding pelanggan vpd](https://user-images.githubusercontent.com/92259942/165211767-e50de170-747f-48a8-8739-ac1ad2c8ddaa.png)

3. Mock up
![boarding](https://user-images.githubusercontent.com/92259942/170866704-9e9efd28-135e-4718-b692-2a18acaa298e.png)

4. Vidio

https://user-images.githubusercontent.com/92259942/170882911-b344b2c8-5016-4fac-8b22-f44c52c609b9.mp4

**Comment by ekkynovrizalam** [comment]
1. memasukkan kode tiket
2. menampilkan data penumpang
3. mencocokkan
4. selesai

**Comment by ekkynovrizalam** [comment]
alternatif path/flow
