### ISSUE TITLE
[S2 - PBI13] Manage Tiket Pelanggan

### ISSUE THREAD

**Issue by TaufikRafli138** [SI-RPL-2022/SI4303_G_TRACSESS#13]
Saya sebagai admin ingin melihat data Tiket Pelanggan , sehingga saya dapat memantau Tiket Pelanggan yang ada 

Nama Usecase : Kelola Data Tiket 
Aktor : Admin dapat mengelola Website khususnya pada fungsi memanage data tiket pelanggan .

Deskripsi Usecase Diagram :
![pni1](https://user-images.githubusercontent.com/31870667/165202911-4d4fb1b8-52be-448c-988a-a19696f6892d.PNG)

Activity Diagram : 
![Mange ka vpd](https://user-images.githubusercontent.com/31870667/165786445-bd406748-f986-4a32-962d-7bd07e627dce.png)

Mock up :
![administrator](https://user-images.githubusercontent.com/92259942/170866724-cae75997-13cd-44ea-ae62-faeab2ec2d61.png)

Video : 

https://user-images.githubusercontent.com/31870667/170896132-c97ae7a3-b205-4d16-a6a7-2848dd4c01b9.mp4

**Comment by ekkynovrizalam** [comment]
fitur hapus nya diganti dengan pembatalan tiket oleh admin
