### ISSUE TITLE
[S2-PBI12] Kelola konfirmasi pembayaran

### ISSUE THREAD

**Issue by aqilahaunia** [SI-RPL-2022/SI4303_G_TRACSESS#14]
Admin dapat melakukan pengelolaan konfirmasi pembayaran customer

Usecase Diagram : 

![13](https://user-images.githubusercontent.com/92071753/165200335-5aed1d00-bb1a-4629-bf30-a3230d86864b.jpg)

Activity Diagram :

![konfirmasi pembayaran](https://user-images.githubusercontent.com/92071753/170886251-d89a5183-c953-4ba8-ad10-496a2caa543c.png)

Mockup :

![konfirmasi pembayaran](https://user-images.githubusercontent.com/92071753/170878570-96dec7d8-3c39-489d-8c1f-110fa6f84546.jpeg)

Video :

https://user-images.githubusercontent.com/92071753/170882722-ec8df814-145b-45c8-b3bf-2b8cae84b695.mp4

**Comment by ekkynovrizalam** [comment]
di ganti konfirmasi manual dengan cara upload bukti transfer
