### ISSUE TITLE
[S3 - PBI 16] Kelola Akun Pribadi

### ISSUE THREAD

**Issue by aqilahaunia** [SI-RPL-2022/SI4303_G_TRACSESS#16]

**Comment by aqilahaunia** [comment]
Customer dapat mengelola akun pribadi

**Comment by aqilahaunia** [comment]
Customer dapat mengelola akun pribadi

Usecase Diagram :

![Kelola akun pribadi](https://user-images.githubusercontent.com/92071753/172286227-3c747ee7-7135-4a3f-9f5c-a1532666bbeb.jpeg)

Activity Diagram :

![kelola akun](https://user-images.githubusercontent.com/92071753/172288497-3ec7fcc7-0b41-40ae-8185-87d2d786edd3.png)


Mockup :

![Ubah Profil1111](https://user-images.githubusercontent.com/92071753/174783612-3b4fd3a1-2c4a-43fe-9d48-25d64a4f07d8.png)


Video :



https://user-images.githubusercontent.com/92071753/174803037-e72accae-45d9-4536-a1d6-5f81a254a3d9.mp4

**Comment by ekkynovrizalam** [comment]
update profil photo
