### ISSUE TITLE
[S3 PBI17] Melihat Stasiun Terakhir yang disinggahi

### ISSUE THREAD

**Issue by TaufikRafli138** [SI-RPL-2022/SI4303_G_TRACSESS#17]
Sebagai  Customer ingin melihat lokasi terkini kereta api yang akan dinaiki. customer dapat melihat statsiun terakhir yang disinggahi oleh kereta api tersebut

Use case diagram : 
<img width="562" alt="Capture" src="https://user-images.githubusercontent.com/31870667/172289439-f2b5e1ad-6f7d-4b03-9f6e-8cfacc8e74de.PNG">

Activity Diagram :

Mockup : 
![Ubah Profil](https://user-images.githubusercontent.com/31870667/172289524-56e84788-f412-4888-87b9-0c8de75bffc1.png)

Video : 

https://user-images.githubusercontent.com/31870667/174848252-d08229d7-3863-4162-8add-9116fcc88dc6.mp4

**Comment by ekkynovrizalam** [comment]
termasuk update data by role stasiun
