### ISSUE TITLE
[S3 - PBI 19] Melihat Tambahan Menu Makanan (Meals on Train)

### ISSUE THREAD

**Issue by aqilahaunia** [SI-RPL-2022/SI4303_G_TRACSESS#19]
1.  Use Case Scenarion
![use case](https://user-images.githubusercontent.com/92259942/172288932-8ad2bcf0-f367-49c9-8785-e5f956ca3b78.png)
2. Activity Diagram
![Meals On Train](https://user-images.githubusercontent.com/92259942/173301386-f2a26602-e6e3-42c8-b321-1e55240b2198.png)
3. Mock Up
![Meals On Train](https://user-images.githubusercontent.com/92259942/173349212-13c6e13d-f6fd-469e-8f72-41aba409db4f.png)
4. Vidio Demo Aplikasi

https://user-images.githubusercontent.com/92259942/174805403-9384aeb9-349a-4085-937f-2c068c09fdad.mp4

**Comment by ekkynovrizalam** [comment]
tambahkan fitur search dan lengkapi dengan mockup

**Comment by ekkynovrizalam** [comment]
search tidak ada
