### ISSUE TITLE
[S1 - PBI2] Mengelola Data Kereta Api

### ISSUE THREAD

**Issue by sascasuhita** [SI-RPL-2022/SI4303_G_TRACSESS#2]
Saya sebagai admin ingin mengelola data kereta api sehingga saya dapat Create, Read, Update, Delete data terkait penumpang kereta api
1. Deskripsi Use Case : 
<img width="407" alt="mengelola data kereta api1" src="https://user-images.githubusercontent.com/92259942/160512398-f80f64bc-4659-40db-8a22-17c8adb8d1e0.png">

2. Activity Diagram : 
![Mengelola data 2 vpd](https://user-images.githubusercontent.com/92259942/160513474-56bbb6a2-1c4e-4e8b-8493-11665c8f69e1.png)

3. Mockup

![mengelola data customer](https://user-images.githubusercontent.com/92259942/170876569-3b4d80c2-b50d-4860-958f-ad2a7af9354d.png)

4. Vidio

https://user-images.githubusercontent.com/92259942/170880801-e870dcd2-b91a-4eed-9c6f-9b4703f5f024.mp4

**Comment by ekkynovrizalam** [comment]
ini activity diagramnya salah. tolong diperbaiki dulu @sascasuhita @TaufikRafli138 @emasdai @reynaldyaditya . tapi PBI nya saya accept

**Comment by sascasuhita** [comment]
> ini activity diagramnya salah. tolong diperbaiki dulu @sascasuhita @TaufikRafli138 @emasdai @reynaldyaditya . tapi PBI nya saya accept

Baik pak, sudah saya coba revisi

**Comment by ekkynovrizalam** [comment]
belum selesai
