### ISSUE TITLE
[S1 - PBI3] - Mengelola Data Stasiun

### ISSUE THREAD

**Issue by aqilahaunia** [SI-RPL-2022/SI4303_G_TRACSESS#3]
Saya sebagai admin ingin melihat data petugas dan data stasiun, sehingga saya dapat memantau siapa petugas kereta api yang sedang bertugas dan kegiatan stasiun
1. Deskripsi Usecase Diagram: 

![crud stasiun](https://user-images.githubusercontent.com/92071753/160513023-7e01f689-0d41-43d0-8bf9-bb0473534ba4.jpeg)

2. Activity Diagram

![crud stasiun (1)](https://user-images.githubusercontent.com/92071753/160240587-6b32d40b-15e7-4d97-87b7-7e2b33881c21.png)

3. Mockup

![Kelola data stasiun](https://user-images.githubusercontent.com/92143585/160253497-14999806-bc24-468c-ac8a-df9faded2b91.png)

**Comment by ekkynovrizalam** [comment]
ini activity dan usecase descriptionnya masih salah contohnya begini 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/62841794/160229308-dac319e5-f171-481a-bbf4-fbe52aaf97a8.png">

**Comment by ekkynovrizalam** [comment]
tp saya accept dan bisa sambil dikerjakan PBI nya
