### ISSUE TITLE
[S1 - PBI4] Mengelola Data Pemesanan Tiket

### ISSUE THREAD

**Issue by aqilahaunia** [SI-RPL-2022/SI4303_G_TRACSESS#6]
Saya sebagai admin ingin dapat melihat data transaksi pemesanan tiket sehingga saya dapat mengelola data pemesanan sehingga tidak adanya data rancu
1. Usecase Diagram : 

![tiket](https://user-images.githubusercontent.com/92071753/160514257-9d8b8663-5503-43df-a702-a4cd1b5d395b.jpeg)

2. Activity Diagram :

![pemesanan tiket (1)](https://user-images.githubusercontent.com/92071753/160241462-b1b40a88-11ad-4d82-a635-c2e6cd2438cc.png)

3. Mockup

![Kelola data tiket kereta](https://user-images.githubusercontent.com/92143585/160253483-f0fbeae3-3e9e-41f2-b5c0-c031030bd4be.png)

**Comment by ekkynovrizalam** [comment]
sama ya ini juga masih salah usecase diagramnya tolong lihat issue #3 

coba dibenerkan jga activitynya. apakah bisa notasi seperti ini ?
<img width="548" alt="image" src="https://user-images.githubusercontent.com/62841794/160229395-a295f178-53a6-417b-8b1d-a26affb73692.png">
