### ISSUE TITLE
[S1 - PBI5] Mengelola Data Petugas

### ISSUE THREAD

**Issue by TaufikRafli138** [SI-RPL-2022/SI4303_G_TRACSESS#7]
Saya sebagai admin ingin melihat data petugas , sehingga saya dapat memantau siapa petugas kereta api yang sedang bertugas dan kegiatan stasiun
Nama UseCase :Mengelola Data Petugas
Aktor : Admin Stasiun yang dapat mengelola Website ini khususnya pada fungsi mengelola data petugas yang ada.

Deskripsi Usecase Diagram:
![WhatsApp Image 2022-03-29 at 08 13 42](https://user-images.githubusercontent.com/92259942/160512867-92a3e266-a2f8-46c5-abda-34ee324d5887.jpeg)

![crud stasiun (1)](https://user-images.githubusercontent.com/31870667/160248017-ae72116c-6b6b-4158-82a0-eae4f96ba4f2.png)

Mockup:
![Kelola data petugas](https://user-images.githubusercontent.com/92143585/160253447-407bc6f0-6977-425f-b31c-cbda820fcc64.png)

**Comment by ekkynovrizalam** [comment]
tidak ada deskripsinya ini
