### ISSUE TITLE
[S1 - PBI9] Memesan Tiket Kereta

### ISSUE THREAD

**Issue by zulfanindar** [SI-RPL-2022/SI4303_G_TRACSESS#9]
Saya sebagai customer ingin melakukan pemesanan tiket sehingga saya dapat melakukan perjalanan menggunakan kereta ke kota tujuan

- Usecase Diagram :

![DESKRIPSI USECASE PBI9](https://user-images.githubusercontent.com/92143585/160523904-b352497e-2ffb-4125-b663-71ff38d581e7.jpeg)

- Activity Diagram :

![Activity Diagram Memesan Tiket Kereta ](https://user-images.githubusercontent.com/92143585/160237656-1d3b86c5-8d8c-4f91-baf2-751e7d3e6a24.png)

- Mockup:

![Halaman Pemesanan](https://user-images.githubusercontent.com/92143585/160252360-02f0abda-ed1d-4f64-a277-73637eeeb3cf.png)

![Hasil Pencarian](https://user-images.githubusercontent.com/92143585/160252377-6604f4e0-8503-4c2e-9ade-8aefa64bbe7c.png)

![Isi Data Diri Pemesanan](https://user-images.githubusercontent.com/92143585/160252383-ddc4ae1e-a3e3-4bfc-972b-977e67e7062b.png)

**Comment by ekkynovrizalam** [comment]
mana diagramnya ??

**Comment by zulfanindar** [comment]
Mohon maaf pak, kemarin saya kurang teliti. Sekarang sudah saya tambahkan pak

**Comment by ekkynovrizalam** [comment]
tambahkan alternative flow nya
